import re
from datetime import UTC, datetime

from models.git_operation import GitOperation
from models.git_push_operation import (
    GitPushOperation,
    PushStatus,
)
from models.task import Task
from models.task_status import TaskStatus
from services.git_service import GitError, GitService

BRANCH_PREFIX = "feature/task-"

DEFAULT_REMOTE = "origin"

SHORT_ID_LENGTH = 8

STOP_WORDS = frozenset(
    {
        "a",
        "an",
        "and",
        "build",
        "create",
        "implement",
        "make",
        "the",
        "with",
        "write",
    }
)

SUMMARY_WORDS = 6


def short_id(task_id: str) -> str:

    cleaned = re.sub(r"[^A-Za-z0-9]", "", task_id)

    return (cleaned[:SHORT_ID_LENGTH] or "unknown").lower()


def branch_name(task_id: str) -> str:

    return f"{BRANCH_PREFIX}{short_id(task_id)}"


def summary(description: str) -> str:
    """A short subject line drawn from the task."""

    words = [
        word
        for word in re.findall(
            r"[A-Za-z0-9]+",
            description.lower(),
        )
        if word not in STOP_WORDS
    ]

    if not words:
        return "apply generated changes"

    return " ".join(words[:SUMMARY_WORDS])


def commit_message(task: Task) -> str:

    lines = [
        f"feat: {summary(task.description)}",
        "",
        "Task:",
        task.description.strip(),
        "",
        "Architecture Score:",
        f"{task.architecture_score}",
        "",
        "Recommendation:",
        task.recommendation.value,
    ]

    if task.generated_files:

        lines += [
            "",
            "Files:",
            *[
                f"- {item.path}"
                for item in task.generated_files
            ],
        ]

    lines += [
        "",
        "Generated by HumanInTheLoop",
    ]

    return "\n".join(lines)


class GitAgent:
    """Turns an approved task into a local branch and commit.

    It never runs before approval and never reaches a
    remote; the service it uses refuses those commands
    outright.
    """

    @staticmethod
    def preview(task: Task) -> dict:
        """What a commit would do, without doing it."""

        return {
            "branch": branch_name(task.id),
            "files": [
                item.path for item in task.generated_files
            ],
            "message": commit_message(task),
        }

    @staticmethod
    def can_commit(task: Task) -> tuple[bool, str]:
        """Whether committing this task is allowed, and why not."""

        if task.status != TaskStatus.APPROVED:
            return (
                False,
                "The task has not been approved yet.",
            )

        if not task.repository_path:
            return (
                False,
                "The task did not record a repository.",
            )

        if not task.generated_files:
            return (
                False,
                "The task generated no files to commit.",
            )

        if not GitService(
            task.repository_path
        ).is_repository():
            return (
                False,
                (
                    "The repository folder is not a git "
                    f"repository: {task.repository_path}"
                ),
            )

        return True, ""

    @staticmethod
    def execute(task: Task) -> GitOperation:

        allowed, reason = GitAgent.can_commit(task)

        if not allowed:
            raise GitError(reason)

        service = GitService(task.repository_path)

        service.require_repository()

        branch = service.checkout_new_branch(
            branch_name(task.id)
        )

        service.add(
            [item.path for item in task.generated_files]
        )

        message = commit_message(task)

        commit_hash = service.commit(message)

        print("=" * 80)
        print("GIT AGENT")
        print("=" * 80)
        print(f"branch: {branch}")
        print(f"commit: {commit_hash[:7]}")
        print("=" * 80)

        return GitOperation(
            branch_name=branch,
            commit_hash=commit_hash,
            commit_message=message,
        )

    @staticmethod
    def push_preview(
        task: Task,
        remote: str = DEFAULT_REMOTE,
    ) -> dict:
        """What a push would send, without sending it."""

        service = GitService(task.repository_path)

        url = ""

        if task.repository_path and service.is_repository():

            try:
                url = service.remote_url(remote)

            except GitError:
                url = ""

        return {
            "remote": remote,
            "remote_url": url,
            "branch": task.git_operation.branch_name
            or branch_name(task.id),
            "files": [
                item.path for item in task.generated_files
            ],
        }

    @staticmethod
    def can_push(
        task: Task,
        remote: str = DEFAULT_REMOTE,
    ) -> tuple[bool, str]:
        """Whether pushing this task is allowed, and why not."""

        if task.status != TaskStatus.APPROVED:
            return (
                False,
                "The task has not been approved yet.",
            )

        if not task.git_operation.committed:
            return (
                False,
                "There is no local commit to push yet.",
            )

        if not task.repository_path:
            return (
                False,
                "The task did not record a repository.",
            )

        service = GitService(task.repository_path)

        if not service.is_repository():
            return (
                False,
                (
                    "The repository folder is not a git "
                    f"repository: {task.repository_path}"
                ),
            )

        if not service.has_remote(remote):
            return (
                False,
                (
                    f"No remote named '{remote}' is "
                    "configured, so there is nowhere to "
                    "push."
                ),
            )

        return True, ""

    @staticmethod
    def push(
        task: Task,
        remote: str = DEFAULT_REMOTE,
    ) -> GitPushOperation:
        """Sends the task's branch to the remote.

        A failure is recorded and returned rather than
        raised, because a push that does not work must not
        undo an approval that does.
        """

        allowed, reason = GitAgent.can_push(task, remote)

        branch = task.git_operation.branch_name

        if not allowed:
            return GitPushOperation(
                branch_name=branch,
                remote_name=remote,
                status=PushStatus.FAILED,
                error=reason,
            )

        service = GitService(task.repository_path)

        url = service.remote_url(remote)

        try:
            service.push_branch(branch, remote)

        except (GitError, OSError) as error:

            print(f"GIT AGENT: push failed: {error}")

            return GitPushOperation(
                branch_name=branch,
                remote_name=remote,
                remote_url=url,
                status=PushStatus.FAILED,
                error=str(error),
            )

        print("=" * 80)
        print("GIT AGENT: pushed")
        print("=" * 80)
        print(f"{remote}/{branch}")
        print("=" * 80)

        return GitPushOperation(
            branch_name=branch,
            remote_name=remote,
            remote_url=url,
            pushed_at=datetime.now(UTC).isoformat(),
            status=PushStatus.SUCCESS,
        )
