from datetime import UTC, datetime

from agents.git_agent import summary
from models.file_type import FileType
from models.pull_request_info import (
    PullRequestInfo,
    PullRequestState,
)
from models.task import Task
from models.task_status import TaskStatus
from services.github_service import (
    GitHubError,
    GitHubService,
)


def section(title: str, items: list[str]) -> str:

    if not items:
        return f"## {title}\n\nNone\n"

    body = "\n".join(f"- {item}" for item in items)

    return f"## {title}\n\n{body}\n"


def description(task: Task) -> str:
    """The pull request body, built from the run itself."""

    sources = [
        item.path
        for item in task.generated_files
        if item.file_type == FileType.SOURCE
    ]

    tests = [
        item.path
        for item in task.generated_files
        if item.file_type == FileType.TEST
    ]

    parts = [
        "## Summary",
        "",
        task.description.strip()
        or "No description was given.",
        "",
        "## Architecture Score",
        "",
        f"{task.architecture_score}",
        "",
        "## Recommendation",
        "",
        task.recommendation.value,
        "",
        "## Review Iterations",
        "",
        f"{task.review_iterations}",
        "",
        section("Generated Files", sources),
        section("Generated Tests", tests),
        section("Structural Findings", task.structural),
        section("Blockers", task.blockers),
        section("Warnings", task.warnings),
        section("Suggestions", task.suggestions),
        "---",
        "",
        (
            "Generated by HumanInTheLoop. Approved by a "
            "human before this branch was pushed."
        ),
    ]

    return "\n".join(parts)


def title(task: Task) -> str:

    return f"feat: {summary(task.description)}"


class PullRequestAgent:
    """Opens a pull request for a pushed, approved task.

    It can create one and read one back. Merging, closing
    and commenting are not implemented, and the service it
    uses refuses those calls outright.
    """

    @staticmethod
    def service(task: Task) -> GitHubService:

        return GitHubService.from_remote(
            task.git_push.remote_url
        )

    @staticmethod
    def can_create(task: Task) -> tuple[bool, str]:
        """Whether a pull request may be opened, and why not."""

        if task.status != TaskStatus.APPROVED:
            return (
                False,
                "The task has not been approved yet.",
            )

        if not task.git_push.pushed:
            return (
                False,
                "The branch has not been pushed yet.",
            )

        if task.pull_request.exists:
            return (
                False,
                (
                    "A pull request already exists for "
                    "this task."
                ),
            )

        try:
            service = PullRequestAgent.service(task)

        except GitHubError as error:
            return False, str(error)

        if not service.has_token:
            return (
                False,
                (
                    "No GitHub token. Set GITHUB_PAT in "
                    ".env to create pull requests."
                ),
            )

        return True, ""

    @staticmethod
    def preview(task: Task) -> dict:
        """What would be opened, without opening it."""

        owner = ""

        repository = ""

        try:
            service = PullRequestAgent.service(task)

            owner = service.owner

            repository = service.repository

        except GitHubError:
            pass

        return {
            "owner": owner,
            "repository": repository,
            "branch": task.git_push.branch_name,
            "title": title(task),
            "body": description(task),
        }

    @staticmethod
    def to_info(
        data: dict,
        branch: str,
        base: str,
    ) -> PullRequestInfo:

        state = PullRequestState.parse(
            data.get("state", "")
        )

        if data.get("merged_at"):
            state = PullRequestState.MERGED

        return PullRequestInfo(
            id=int(data.get("number") or 0),
            url=str(data.get("html_url") or ""),
            branch=branch,
            base=base,
            state=state,
            created_at=str(data.get("created_at") or ""),
        )

    @staticmethod
    def execute(
        task: Task,
        base: str = "",
    ) -> PullRequestInfo:
        """Opens the pull request, or records why it failed.

        A failure is returned rather than raised, because
        it must not undo the approval, the commit or the
        push that already succeeded.
        """

        branch = task.git_push.branch_name

        allowed, reason = PullRequestAgent.can_create(task)

        if not allowed:
            return PullRequestInfo(
                branch=branch,
                state=PullRequestState.FAILED,
                error=reason,
            )

        try:
            service = PullRequestAgent.service(task)

            existing = service.find_pull_request(branch)

            if existing:

                print(
                    "PULL REQUEST AGENT: one already "
                    f"exists for {branch}"
                )

                return PullRequestAgent.to_info(
                    existing,
                    branch,
                    str(
                        (existing.get("base") or {}).get(
                            "ref"
                        )
                        or base
                    ),
                )

            target = base or service.default_branch()

            data = service.create_pull_request(
                branch,
                target,
                title(task),
                description(task),
            )

            info = PullRequestAgent.to_info(
                data,
                branch,
                target,
            )

            if not info.created_at:
                info.created_at = datetime.now(
                    UTC
                ).isoformat()

            print("=" * 80)
            print("PULL REQUEST AGENT")
            print("=" * 80)
            print(f"{info.label} {info.state.value}")
            print(info.url)
            print("=" * 80)

            return info

        except (GitHubError, OSError, ValueError) as error:

            print(f"PULL REQUEST AGENT: failed: {error}")

            return PullRequestInfo(
                branch=branch,
                base=base,
                state=PullRequestState.FAILED,
                error=str(error),
            )

    @staticmethod
    def refresh(task: Task) -> PullRequestInfo:
        """Reads the current state of an existing request."""

        info = task.pull_request

        if not info.id:
            return info

        try:
            service = PullRequestAgent.service(task)

            data = service.read_pull_request(info.id)

        except (GitHubError, OSError, ValueError) as error:

            print(f"PULL REQUEST AGENT: read failed: {error}")

            return info

        return PullRequestAgent.to_info(
            data,
            info.branch,
            info.base,
        )
